### ISSUE TITLE
Root file reads in correctly in 0.3.0 but not in master. JaggedArray has improper offsets as result.

### ISSUE THREAD

**Issue by lgray** [spark-root/laurelin#59]
On the following root file:
```root://cmseos.fnal.gov/store/group/lpccoffea/coffeabeans/102X/nano_2018/QCD_HT2000toInf_TuneCP5_13TeV-madgraphMLM-pythia8/NanoTuples-2018_RunIIAutumn18MiniAOD-102X_v15-v1/190321_064928/0000/nano_4.root``` 

in master, starting from basket 20 (counting from zero), when reading a jagged array that has been put into spark from laurelin:
```
19/09/23 14:55:22 WARN scheduler.TaskSetManager: Lost task 11.0 in stage 7.0 (TID 30, localhost, executor driver): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/opt/spark/python/lib/pyspark.zip/pyspark/worker.py", line 377, in main
    process()
  File "/opt/spark/python/lib/pyspark.zip/pyspark/worker.py", line 372, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/opt/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 286, in dump_stream
    for series in iterator:
  File "<string>", line 1, in <lambda>
  File "/opt/spark/python/lib/pyspark.zip/pyspark/worker.py", line 101, in <lambda>
    return lambda *a: (verify_result_length(*a), arrow_return_type)
  File "/opt/spark/python/lib/pyspark.zip/pyspark/worker.py", line 92, in verify_result_length
    result = f(*a)
  File "/opt/spark/python/lib/pyspark.zip/pyspark/util.py", line 99, in wrapper
    return f(*args, **kwargs)
  File "<string>", line 22, in coffea_udf
  File "/home/lagray/py36/lib64/python3.6/site-packages/coffea/processor/test_items/NanoTestProcessor.py", line 47, in process
    dimuon = muon.distincts()
  File "/home/lagray/py36/lib64/python3.6/site-packages/coffea/analysis_objects/JaggedCandidateArray.py", line 324, in distincts
    outs = super(JaggedCandidateMethods, self).distincts(nested)
  File "/home/lagray/py36/lib64/python3.6/site-packages/awkward/array/jagged.py", line 1255, in distincts
    argpairs = self._argdistincts(absolute=True)
  File "/home/lagray/py36/lib64/python3.6/site-packages/awkward/array/jagged.py", line 1082, in _argdistincts
    counts_comb = self.counts*(self.counts - 1) // 2
  File "/home/lagray/py36/lib64/python3.6/site-packages/awkward/array/jagged.py", line 375, in counts
    self._valid()
  File "/home/lagray/py36/lib64/python3.6/site-packages/awkward/array/jagged.py", line 466, in _valid
    raise ValueError("maximum offset {0} is beyond the length of the content ({1})".format(self._offsets.max(), len(self._content)))
ValueError: maximum offset 1472 is beyond the length of the content (1442)

	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:452)
	at org.apache.spark.sql.execution.python.ArrowPythonRunner$$anon$1.read(ArrowPythonRunner.scala:172)
	at org.apache.spark.sql.execution.python.ArrowPythonRunner$$anon$1.read(ArrowPythonRunner.scala:122)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:406)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at org.apache.spark.sql.execution.python.ArrowEvalPythonExec$$anon$2.<init>(ArrowEvalPythonExec.scala:98)
	at org.apache.spark.sql.execution.python.ArrowEvalPythonExec.evaluate(ArrowEvalPythonExec.scala:96)
	at org.apache.spark.sql.execution.python.EvalPythonExec$$anonfun$doExecute$1.apply(EvalPythonExec.scala:127)
	at org.apache.spark.sql.execution.python.EvalPythonExec$$anonfun$doExecute$1.apply(EvalPythonExec.scala:89)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
```

I'll shoot you the testing script on slack.

The same file works fine in 0.3.0, so something corrupting the JaggedArray unpacking in master.

**Comment by PerilousApricot** [comment]
This actually blows up in bare java as well by just doing a `collectAsList()` on the dataframe

**Comment by PerilousApricot** [comment]
Unfortunately, this is gonna take some yak shaving to figure out the lower level code. It appears there's some sort of indexing oopsie down in the basement, and there's no substantial tests at that level, so fixing this is gonna take some time to first write a whole harness for that level, injecting the byte stream from your example file, and then actually figuring out the issue.

**Comment by PerilousApricot** [comment]
```java
    @Test
    public void testLoadDataFrame() {
        Dataset<Row> df = spark
                .read()
                .format("edu.vanderbilt.accre.laurelin.Root")
                .option("tree",  "Events")
                .load("testdata/pristine/nano_4.root");
        df = df.select("nMuon","Muon_pt","Muon_eta","Muon_phi","Muon_mass");
        df.show();
        List<Row> ret = df.collectAsList();
        System.out.println(ret);
        assertEquals(49928, df.count());
    }
```
This is explodey with 46e5e5064c67cc2f269969700bf0edc4008183c1 .. descending into the dungeon

**Comment by PerilousApricot** [comment]
lower
```java
    @Test
    public void testLoadVectorColumns2() throws IOException {
        Map<String, String> optmap = new HashMap<String, String>();
        optmap.put("path", "testdata/pristine/nano_4.root");
        optmap.put("tree",  "Events");
        optmap.put("threadCount", "0");
        DataSourceOptions opts = new DataSourceOptions(optmap);
        Root source = new Root();
        TTreeDataSourceV2Reader reader = (TTreeDataSourceV2Reader) source.createReader(opts, null);
        List<InputPartition<ColumnarBatch>> partitionPlan = reader.planBatchInputPartitions();
        assertNotNull(partitionPlan);
        StructType schema = reader.readSchema();

        InputPartition<ColumnarBatch> partition = partitionPlan.get(0);
        InputPartitionReader<ColumnarBatch> partitionReader = partition.createPartitionReader();
        assertTrue(partitionReader.next());
        ColumnarBatch batch = partitionReader.get();
```
^ this explodes with an error in ArrayBuilder .. going lower

**Comment by PerilousApricot** [comment]
well, cool. 
```
java.lang.IllegalArgumentException
	at java.nio.Buffer.limit(Buffer.java:275)
	at edu.vanderbilt.accre.laurelin.array.RawArray.slice(RawArray.java:34)
	at edu.vanderbilt.accre.laurelin.array.ArrayBuilder$CallableFill.call(ArrayBuilder.java:217)
	at edu.vanderbilt.accre.laurelin.array.ArrayBuilder.<init>(ArrayBuilder.java:135)
	at edu.vanderbilt.accre.laurelin.spark_ttree.TTreeColumnVector.<init>(TTreeColumnVector.java:52)
	at edu.vanderbilt.accre.laurelin.Root$TTreeDataSourceV2PartitionReader.getBatchRecursive(Root.java:188)
	at edu.vanderbilt.accre.laurelin.Root$TTreeDataSourceV2PartitionReader.get(Root.java:161)
	at edu.vanderbilt.accre.laurelin.Root$TTreeDataSourceV2PartitionReader.get(Root.java:98)
	at edu.vanderbilt.accre.spark_ttree.TTreeDataSourceUnitTest.testLoadVectorColumns2(TTreeDataSourceUnitTest.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
```

**Comment by PerilousApricot** [comment]
FWIW, this patch fixed your local test, but boofed the other existing tests. If you want to reproduce, checkout 39123fa1e3f29ecce5c039f7f2ac89189ad197ea and then apply to fix up a compilation error in the testing:

```patch
diff --git a/src/main/java/edu/vanderbilt/accre/laurelin/root_proxy/TTree.java b/src/main/java/edu/vanderbilt/accre/laurelin/root_proxy/TTree.java
index 23e2cb3..dfad535 100644
--- a/src/main/java/edu/vanderbilt/accre/laurelin/root_proxy/TTree.java
+++ b/src/main/java/edu/vanderbilt/accre/laurelin/root_proxy/TTree.java
@@ -27,6 +27,10 @@ public class TTree {
     private long entryStart;
     private long entryStop;
 
+    public TTree(Proxy data, TFile file) {
+        this(data,file,-1,-1);
+    }
+
     public TTree(Proxy data, TFile file, long entryStart, long entryStop) {
         this.data = data;
         this.file = file;
```
I was (in that other PR), working on a branch w/those on top and couldn't get things to work, but checking out those commits directly is also not clicking :/ Still looking through it.

**Comment by PerilousApricot** [comment]
Grr. This was the error in TTreeColumnVectorUnitTest that I'm hitting, which I think is unrelated, but if you wanna add as well:
```java
    @Test
    public void testSliceI32_partial() throws IOException {
        TFile file = TFile.getFromFile("testdata/all-types.root");
        TTree tree = new TTree(file.getProxy("Events"), file);
        TBranch branch = tree.getBranches("SliceI32").get(0);
        Cache cache = new Cache();
        SlimTBranchInterface slim = SlimTBranch.getFromTBranch(branch);

        TTreeColumnVector result = new TTreeColumnVector(new ArrayType(new IntegerType(), false), new SimpleType.ArrayType(SimpleType.fromString("int")), SimpleType.dtypeFromString("int"), cache, 0, 6, slim, null);
        ColumnarArray event0 = result.getArray(0);
        assertEquals(event0.numElements(), 0);
        ColumnarArray event1 = result.getArray(1);
        assertEquals(event1.numElements(), 1);
        assertEquals(1, event1.getInt(0));
        ColumnarArray event2 = result.getArray(2);
        assertEquals(event2.numElements(), 2);
        assertEquals(2, event2.getInt(0));
        assertEquals(2, event2.getInt(1));
        ColumnarArray event3 = result.getArray(3);
        assertEquals(event3.numElements(), 0);
        ColumnarArray event4 = result.getArray(4);
        assertEquals(event4.numElements(), 1);
        assertEquals(-2147483647, event4.getInt(0));
        ColumnarArray event5 = result.getArray(5);
        assertEquals(event5.numElements(), 2);
        assertEquals(-2147483646, event5.getInt(0));
        assertEquals(-2147483646, event5.getInt(1));
    }
```

**Comment by lgray** [comment]
This one should be fixed now I get no differences with respect to uproot locally.
The branch will be pushed in a bit.
