### ISSUE TITLE
Paths with GLOB patterns don't work

### ISSUE THREAD

**Issue by ingomueller-net** [spark-root/laurelin#81]
I am not 100% sure where the problem is, but paths with GLOB patterns (e.g., `"test.*.root"`) currently do not work. Here's how to reproduce what I would like to achieve:

```python
import argparse

import pyspark.sql

parser = argparse.ArgumentParser()
parser.add_argument('-i', '--input', help='Input ROOT file')
parser.add_argument('-t', '--tree',  help='Name of tree to open', default='Events')
args = parser.parse_args()

spark = pyspark.sql.SparkSession.builder \
    .config('spark.jars.packages', 'edu.vanderbilt.accre:laurelin:1.0.0') \
    .getOrCreate()
sc = spark.sparkContext
df = spark.read.format('root') \
                .option('tree', args.tree) \
                .load(args.input)
df.printSchema()
print('Number of rows:', df.count())
```

Providing any path with pattern via `-i` raises the following error:

```
Traceback (most recent call last):
  File "/home/muellein/git/root-playground/laurelin/python/hello-world.py", line 17, in <module>
    .load(args.input)
  File "/mnt/scratch/muellein/download/spark-2.4.4-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 166, in load
  File "/mnt/scratch/muellein/download/spark-2.4.4-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/mnt/scratch/muellein/download/spark-2.4.4-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/mnt/scratch/muellein/download/spark-2.4.4-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o34.load.
: edu.vanderbilt.accre.repackaged.guava.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: java.io.FileNotFoundException: ~/test.*.root (No such file or directory)
        at edu.vanderbilt.accre.repackaged.guava.cache.LocalCache$Segment.get(LocalCache.java:2051)
        at edu.vanderbilt.accre.repackaged.guava.cache.LocalCache.get(LocalCache.java:3953)
        at edu.vanderbilt.accre.repackaged.guava.cache.LocalCache.getOrLoad(LocalCache.java:3976)
        at edu.vanderbilt.accre.repackaged.guava.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4960)
        at edu.vanderbilt.accre.laurelin.Root.createReader(Root.java:576)
        at edu.vanderbilt.accre.laurelin.Root.createReader(Root.java:564)
        at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Relation$SourceHelpers.createReader(DataSourceV2Relation.scala:155)
        at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Relation$.create(DataSourceV2Relation.scala:172)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:204)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: ~/test.*.root (No such file or directory)
        at edu.vanderbilt.accre.laurelin.Root$TTreeDataSourceV2Reader.<init>(Root.java:272)
        at edu.vanderbilt.accre.laurelin.Root$1.load(Root.java:528)
        at edu.vanderbilt.accre.laurelin.Root$1.load(Root.java:514)
        at edu.vanderbilt.accre.repackaged.guava.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
        at edu.vanderbilt.accre.repackaged.guava.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
        at edu.vanderbilt.accre.repackaged.guava.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
        at edu.vanderbilt.accre.repackaged.guava.cache.LocalCache$Segment.get(LocalCache.java:2045)
        ... 20 more
Caused by: java.io.FileNotFoundException: ~/test.*.root (No such file or directory)
        at java.io.RandomAccessFile.open0(Native Method)
        at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:124)
        at edu.vanderbilt.accre.laurelin.root_proxy.NIOFile.<init>(NIOFile.java:28)
        at edu.vanderbilt.accre.laurelin.root_proxy.IOFactory.openForRead(IOFactory.java:33)
        at edu.vanderbilt.accre.laurelin.root_proxy.ROOTFileCache.load(ROOTFileCache.java:229)
        at edu.vanderbilt.accre.laurelin.root_proxy.ROOTFileCache.getROOTFile(ROOTFileCache.java:168)
        at edu.vanderbilt.accre.laurelin.Root$TTreeDataSourceV2Reader.<init>(Root.java:266)
        ... 26 more
```

If you replace `'root'` with `'csv'` as format and point to a set of CSV files, the same code works. I have tried to understand a bit how unglobbing works in Spark, but haven't quite managed. However it should work, it seems to work with CSV but not with Laurelin.

**Comment by PerilousApricot** [comment]
I think that I need to properly handle expanding the tilde out.. let me try that and get back to you

**Comment by ingomueller-net** [comment]
Maybe that's another problem. But it also doesn't work in a path without tilde:

```
py4j.protocol.Py4JJavaError: An error occurred while calling o34.load.
: edu.vanderbilt.accre.repackaged.guava.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: java.io.FileNotFoundException: /home/muellein/test.*.root (No such file or directory)
```

**Comment by PerilousApricot** [comment]
OK, I found the issue and I'm working on a fix that should be out later today (I've gotta do something with "my other hat" this morning).

**Comment by PerilousApricot** [comment]
OK, I've worked on this a bit, and I've got a solution for the globbing, but I'm having trouble duplicating the `~` expansion with the CSV reader. The following testcase fails for me, and I'm unsure if there's something weird in my environment that's not working.

```java
    @Test
    public void testLoadDataFrameCSV() {
        Dataset<Row> df = spark
                .read()
                .csv("~/projects/eclipse-workspace/spark-ttree/*.csv");
        df.show();
        assertEquals(100, df.count());
    }
```

Expanding the tilde manually DOES work, so I'm trying to see what's weird on my laptop that's keeping me from being able to do that.

**Comment by PerilousApricot** [comment]
@ingomueller-net Could you confirm that the CSV reader properly expands `~` in your environment? I'm trying to duplicate its behavior and am struggling with that part. I wonder if your hdfs configs are different and that's triggering different behavior

**Comment by ingomueller-net** [comment]
Sorry for not replying earlier. Expanding tilde does not work for me either:

```
pyspark.sql.utils.AnalysisException: u'Path does not exist: file:/home/muellein/~/wh001200.csv;'
```

For me, the issue is solved even if `*` works, but `~` doesn't.

**Comment by PerilousApricot** [comment]
I guess in that case, the question is -- do you want me to replicate the
behavior of the CSV reader, or is it important that tildes be expanded? If
you don't need to expand home directories, then I have a patch ready to go
-- 
It's dark in this basement.

**Comment by PerilousApricot** [comment]
Ah, I misread your response. I'll put together the patch and add some additional tests, I'll try to get the release tonight
